name: ttx

on:
  push:
  # allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: ls -al
      - run: pip install fonttools
      - run: ttx -t "OS/2" sarasa-mono-tc-regular.ttf
      - run: ttx -t "OS/2" sarasa-mono-tc-regular-nerd-font.ttf
      - run: ls -al
      - run: cat sarasa-mono-tc-regular.ttx
      - run: cat sarasa-mono-tc-regular-nerd-font.ttx
      - run: |
          origin_width="$(grep xAvgCharWidth sarasa-mono-tc-regular.ttx | cut -d '"' -f 2)"
          echo $width
          sed -i "s/xAvgCharWidth\ value=\"[0-9]\+\"/xAvgCharWidth\ value=\"${origin_width}\"/g" sarasa-mono-tc-regular-nerd-font.ttx
      - run: cat sarasa-mono-tc-regular-nerd-font.ttx
      - run: mv sarasa-mono-tc-regular-nerd-font.ttf sarasa-mono-tc-regular-nerd-font.origin.ttf
      - run: ttx -o sarasa-mono-tc-regular-nerd-font.ttf -m sarasa-mono-tc-regular-nerd-font.origin.ttf sarasa-mono-tc-regular-nerd-font.ttx
      - run: ls -al
      - uses: actions/upload-artifact@v2
        with:
          name: after ttx
          path: 'sarasa-mono-tc-regular-nerd-font.ttf'

      - name: build hdmx
        run: python build-hdmx-for-sarasa.py sarasa-mono-tc-regular-nerd-font.ttf
      - run: ls -al
      - uses: actions/upload-artifact@v2
        with:
          name: after hdmx
          path: 'hdmx-sarasa-mono-tc-regular-nerd-font.ttf'
