name: ttx

on:
  # allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: ls -al
      - run: pip install fonttools
      - run: env | sort
      - run: python /opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/fontTools/ttx.py -t "OS/2" sarasa-mono-tc-regular-nerd-font.ttf
      - run: ls -al
      - run: cat sarasa-mono-tc-regular-nerd-font.ttx
      - run: sed -i "s/xAvgCharWidth\ value=\"[0-9]\+\"/xAvgCharWidth\ value=\"500\"/g" sarasa-mono-tc-regular-nerd-font.ttx
      - run: cat sarasa-mono-tc-regular-nerd-font.ttx
      - run: python /opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/fontTools/ttx.py -m sarasa-mono-tc-regular-nerd-font.ttf sarasa-mono-tc-regular-nerd-font.ttx
      - run: ls -al
      - run: rm sarasa-mono-tc-regular-nerd-font.ttf
      - uses: actions/upload-artifact@v2
        with:
          name: after ttx
          path: '*.ttf'
