name: ttx

on:
  # allow manually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install fonttools
      - run: env | sort
      - run: /opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/fontTools/ttx.py -t "OS/2" sarasa-mono-tc-regular-nerd-font.ttf
      - run: ls -l
